version: "3.1"

services:
  mongo:
    image: mongo:6
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: <admin-user>
    #   MONGO_INITDB_ROOT_PASSWORD: <admin-password>
    #   MONGO_INITDB_DATABASE: <database to create>
    volumes:
      - ./db_data/:/data/db/
      - /etc/timezone:/etc/timezone:ro

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo_ui
    ports:
      - 8081:8081
    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: <admin-user>
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: <admin-password>
    #   ME_CONFIG_MONGODB_URL: mongodb://<admin-user>:<admin-password>@mongo:27017/
